remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

title: Gleynner Ghiotto Lima de Menezes
logo: /assets/img/logo.png
description: Em construção.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
